### ISSUE TITLE
Execute methods missing

### ISSUE THREAD

**Issue by byrotron** [marmol-dev/thinky.d.ts#1]
Hi,

I'm not sure if this is an issue or if i am using it incorrectly, as i am new to Thinky. However, there does not seem to be a definition for the execute() method.

**Comment by marmol-dev** [comment]
Hi @byrotron.
No, there is no definition of the `execute` method. There are no definitions for some methods, this project is not manteined. If stability is important to you I would suggest to look for a better solution. 
Regards.
